#server:
#  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

#Actuator
info:
  app:
    name: Sample Gateway Service
    description: Service to forward requests to the appropriate microservice
management:
  endpoint:
    health:
      show-details: always